force-app/main/default/objects/TestCustomObject__c/TestCustomObject__c.object-meta.xml
<CustomObject>
    <description>Test Object for exercises</description>
    <label>TestCustomObject</label>
    <nameField>
        <label>TestCustomObject Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>TestCustomObjects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/TestCustomObject__c/fields/NumberValue__c.field-meta.xml
<CustomField>
    <fullName>NumberValue__c</fullName>
    <description>Test number value</description>
    <label>NumberValue</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/TestCustomObject__c/fields/TestCheckboxValue__c.field-meta.xml
<CustomField>
    <fullName>TestCheckboxValue__c</fullName>
    <defaultValue>false</defaultValue>
    <label>TestCheckboxValue</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/TestCustomObject__c/fields/TestPicklistValue__c.field-meta.xml
<CustomField>
    <fullName>TestPicklistValue__c</fullName>
    <label>TestPicklistValue</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FirstOption</fullName>
            </value>
            <value>
                <fullName>SecondOption</fullName>
            </value>
            <value>
                <fullName>ThirdOption</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestObjectToWrapperConverter.cls
public with sharing class TestObjectToWrapperConverter {

    public TestCustomObjectWrapper convert(TestCustomObject__c obj) {
        return TestCustomObjectWrapper.builder()
                .withName(obj.Name)
                .withId(obj.Id)
                .withNumberValue(obj.NumberValue__c)
                .withCheckboxValue(obj.TestCheckboxValue__c)
                .withPicklistValue(obj.TestPicklistValue__c)
                .build();
    }

}